### ISSUE TITLE
Cannot compile using Xcode 12

### ISSUE THREAD

**Issue by colinmacleod** [urbanairship/ua-unity-plugin#121]
Use of undeclared identifier '_style'; did you mean 'style'?

Same issue that was resolved on iOS - looks like Unity Plugin needs an update.

https://github.com/urbanairship/ios-library/issues/249

(I sent a support ticket about this)

**Comment by marc-scig** [comment]
Hi @colinmacleod,

We're in the process of updating the plugin with the latest SDK, which fixes that problem. The code is in review, so I'll let you know when it's released.

**Comment by colinmacleod** [comment]
Great - thanks for the update

**Comment by srinadh-k** [comment]
@marc-scig we are also facing a compilation issue. any update when it will be available?

`Library not found for -lAirshipExtensions`

**Comment by rlepinski** [comment]
@srinadh-k are you using unity? could you please open a new issue if you are?

**Comment by srinadh-k** [comment]
@rlepinski  No, that was my bad and I create [a new ticket](https://github.com/urbanairship/ios-library/issues/258).

**Comment by rlepinski** [comment]
@colinmacleod I am having issues with Xcode 12 and Unity. What version fo Unity are you using? You could fix the build issue for you right now by forcing `13.5.6` pod by updating the `UADepdendencies.xml` file

**Comment by colinmacleod** [comment]
@rlepinski Thanks for. that - I'n using 2019.2.21f1
Where do I find that file?

**Comment by rlepinski** [comment]
`Assets -> UrbanAirship -> Editor -> UADependencies.xml`

I was able to resolve the build issues with Unity. I hopefully will have a release today. I can give you a build if you want to verify it works for you.

**Comment by colinmacleod** [comment]
@rlepinski Ah the file was mistyped above - I cut pasted UADepdendencies.xml
Thanks on the fix and yeah I'll take you up on the release if it's avail 👍

**Comment by rlepinski** [comment]
[urbanairship-8.0.0.unitypackage.zip](https://github.com/urbanairship/ua-unity-plugin/files/5284789/urbanairship-8.0.0.unitypackage.zip)


I was able to get iOS to build. Having an issue with Android not picking up the `urbanairship-resources` directory, but I think thats an issue with the latest unity and not with the plugin

**Comment by colinmacleod** [comment]
Great - thank you so much. We're not live on Android yet, so it will be super to have the iOS fix.

**Comment by rlepinski** [comment]
[urbanairship-8.0.0.unitypackage.zip](https://github.com/urbanairship/ua-unity-plugin/files/5284936/urbanairship-8.0.0.unitypackage.zip)

Updated package. You probably will want to get the latest once we do an actual release. Right now this build is looking good.

**Comment by rlepinski** [comment]
@colinmacleod if you use landing pages with custom urls, not airship ones, you probably want to add `*` to the URL Scope Open in the config page.

**Comment by colinmacleod** [comment]
Nice - will do!

Thanks again.

**Comment by rlepinski** [comment]
8.0.0 is out!
