### ISSUE TITLE
UAUnityPlugin channelRegistrationSucceeded:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by colinmacleod** [urbanairship/ua-unity-plugin#122]
Urban Airship 8.0.0
Unity 2019.2.21f1
iOS 13.6.1
Xcode 12.0

Project builds in Unity and Xcode builds.

When I try to play on device from Xcode, on startup, I always get this issue:

2020-10-01 15:40:35.349243-0600 PROJECTNAME[425:96444] [I] -[UAChannel registrationSucceeded] [Line 402] Channel registration updated successfully.
2020-10-01 15:40:35.349419-0600 PROJECTNAME[425:96444] -[UAUnityPlugin channelRegistrationSucceeded:]: unrecognized selector sent to instance 0x2835df4e0
2020-10-01 15:40:35.363514-0600 PROJECTNAME[425:96444] Uncaught exception: NSInvalidArgumentException: -[UAUnityPlugin channelRegistrationSucceeded:]: unrecognized selector sent to instance 0x2835df4e0
(
	0   CoreFoundation                      0x0000000185a3d358 7769FFAC-4FCD-332D-A4BE-DA2F0E2FFEA5 + 1250136
	1   libobjc.A.dylib                     0x0000000185752cc0 objc_exception_throw + 60
	2   CoreFoundation                      0x000000018593c110 7769FFAC-4FCD-332D-A4BE-DA2F0E2FFEA5 + 196880
	3   CoreFoundation                      0x0000000185a41b20 7769FFAC-4FCD-332D-A4BE-DA2F0E2FFEA5 + 1268512
	4   CoreFoundation                      0x0000000185a43e10 _CF_forwarding_prep_0 + 96
	5   CoreFoundation                      0x0000000185995824 7769FFAC-4FCD-332D-A4BE-DA2F0E2FFEA5 + 563236
	6   CoreFoundation                      0x0000000185995874 7769FFAC-4FCD-332D-A4BE-DA2F0E2FFEA5 + 563316
	7   CoreFoundation                      0x0000000185994b64 7769FFAC-4FCD-332D-A4BE-DA2F0E2FFEA5 + 559972
	8   CoreFoundation                      0x0000000185994818 7769FFAC-4FCD-332D-A4BE-DA2F0E2FFEA5 + 559128
	9   CoreFoundation                      0x000000018590e058 7769FFAC-4FCD-332D-A4BE-DA2F0E2FFEA5 + 8280
	10  CoreFoundation                      0x0000000185994158 _CFXNotificationPost + 1260
	11  Foundation                          0x0000000185d07e2c 14223DB5-7AE5-302A-9495-DE26DA6F9724 + 28204
	12  PROJECTNAME                                 0x0000000104e701b8 -[UAChannel registrationSucceeded] + 264
	13  PROJECTNAME                                 0x0000000104e74118 -[UAChannelRegistrar succeededWithPayload:] + 184
	14  PROJECTNAME                                 0x0000000104e73c34 __47-[UAChannelRegistrar

**Comment by marc-scig** [comment]
Hi @colinmacleod,

Thanks for the report. We'll take a look at it and see if we can figure out what's going on here.

**Comment by colinmacleod** [comment]
Thank you!
--
Colin MacLeod
+1 (512) 412-8838

**Comment by marc-scig** [comment]
OK I think I see the issue, it looks like there's a mistyped selector in the plugin. We'll have a patch in the works soon, and I'll keep you posted.

**Comment by colinmacleod** [comment]
Thanks, Marc!
--
Colin MacLeod
+1 (512) 412-8838

**Comment by marc-scig** [comment]
@colinmacleod 8.0.1 is out and should fix your issue. Let us know if you have any other problems, though.

**Comment by colinmacleod** [comment]
Looking good - thank you!
