### ISSUE TITLE
Docs need an update

### ISSUE THREAD

**Issue by adavies25** [urbanairship/ua-unity-plugin#124]
Hello,

The docs here say XCode 11+ is required for the Unity UA plugin:
https://docs.airship.com/platform/unity/getting-started/

Here in the Unity UA plugin change log for version 8.0.0 it says XCode 12+ is now required.
https://github.com/urbanairship/ua-unity-plugin/blob/main/CHANGELOG.md

Please update the above document to reflect XCode 12+ is now required.

Thanks,
Alan

**Comment by marc-scig** [comment]
Hi @adavies25,

Thanks for the feedback. We'll get this updated soon.
