### ISSUE TITLE
Push Notifications Not Received with Firebase Analytics

### ISSUE THREAD

**Issue by aschau** [urbanairship/ua-unity-plugin#81]
# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.
Using Urban Airship Unity Package v5.1.0.

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.
Unity Version 2017.3.1p4

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.
I am trying to use Firebase analytics along with Urban Airship push notifications at the same time. Push notifications originally worked before adding the latest firebase analytics package.
**Android:**
Now the analytics events go through to my firebase panel and urban airship appears to take off fine, but push notifications are no longer received.

### What is the expected behavior?
ℹ Please provide a brief description of the expected behavior here.
Analytics are reported correctly and push notifications are able to be received.

### What are the steps to reproduce the unexpected behavior?
ℹ Please provide reproduction steps here.

1. Import urban airship package
2. Import [firebase analytics/messaging package](https://firebase.google.com/download/unity)

### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.
Log if I don't have the Firebase Messaging Package added:
`Java class com/google/firebase/messaging/cpp/RegistrationIntentService not found.  Please verify the AAR which contains the com/google/firebase/messaging/cpp/RegistrationIntentService class is included in your app.`

**Comment by marc-scig** [comment]
@aschau can you provide us more information about the steps you went through? are you adding the messaging package in order to fix a different problem?

**Comment by aschau** [comment]
@BrianBatchelder @marc-scig  Thanks for getting back to me. I had initially imported the FirebaseAnalytics.unitypackage from that link I inserted above, but received the error I listed at the bottom of my report. As a result, I had to import the FirebaseMessaging UnityPackage in order to avoid the issues. It might be related to the "FirebaseApp.CheckDependencies" function call which is listed here: https://firebase.google.com/docs/analytics/unity/start.


`09-11 15:51:30.311 15189-15218/ E/firebase: Java class com/google/firebase/messaging/cpp/RegistrationIntentService not found.  Please verify the AAR which contains the com/google/firebase/messaging/cpp/RegistrationIntentService class is included in your app.`

`09-11 15:51:30.314 15189-15218/ E/Unity: Java class com/google/firebase/messaging/cpp/RegistrationIntentService not found.  Please verify the AAR which contains the com/google/firebase/messaging/cpp/RegistrationIntentService class is included in your app.`

`    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:LogError(Object)
    Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String)
    Firebase.FirebaseApp:LogMessage(LogLevel, String)
    Firebase.AppUtilPINVOKE:FirebaseApp_CreateInternal__SWIG_0()
    Firebase.FirebaseApp:CreateInternal()
    Firebase.FirebaseApp:<Create>m__0()
    Firebase.FirebaseApp:CreateAndTrack(CreateDelegate, FirebaseApp)
    Firebase.FirebaseApp:Create()
    Firebase.FirebaseApp:get_DefaultInstance()
    Firebase.FirebaseApp:CheckDependenciesInternal()
    Firebase.<CheckDependencies>c__AnonStorey2:<>m__0()
    Firebase.FirebaseApp:TranslateDllNotFoundException(Action)
    Firebase.FirebaseApp:CheckDependencies()
`

**Comment by rlepinski** [comment]
@aschau Are you enabling the Play Services Jar Resolver? It should pull in the missing package. Do you have a sample project that you can share that reproduces the issue?

**Comment by aschau** [comment]
Yes, I have the Play Services Jar Resolver and I've tried resolving and force resolving, but it doesn't seem to fix the issue. I have a sample project ready, but do you have an email that I can share it to?

**Comment by rlepinski** [comment]
Please email it to support@urbanairship.com and ill try to take a look today or early next week.

**Comment by rlepinski** [comment]
@aschau I am having a hard time building the project due to some dex mege issues... so it might take me another day or so.

I noticed that your FCM sender ID does not match the google-services.json file you provided. I think you need to update UA Settings (Window -> Urban Airship) with:

- Clear the fcm sender IDs (it will pick it up from the google-services.json)
- Turn off `Process google-services`, let the other firebase projects generate it

Then try again? Could you enable verbose logs and email them to us if it still does not work?

**Comment by aschau** [comment]
The reason the jsons didn't match for that sample project is because I was making sure it wasn't just my firebase project that it wasn't working with. In my actual project, it has the same result. I can try the things you suggested though and let you know.

**Comment by rlepinski** [comment]
The solution to this is to create an Android Library project that extends the cpp unity service listeners and calls through to the UA SDK. Here is a branch: https://github.com/urbanairship/ua-unity-plugin/tree/firebase-compat with the work needed. I am not sure how feasible this is to include by default, as it requires the cpp libraries. The actual solution would be for firebase to support more than 1 listener services for messaging and registration events. I am going to close as will not fix, but I will keep the branch alive incase anyone else needs it. Here is a drop in aar that can be used to resolve the issue. Make sure to unzip it first.
[firebase-compat-release.aar.zip](https://github.com/urbanairship/ua-unity-plugin/files/2416487/firebase-compat-release.aar.zip)
