### ISSUE TITLE
UAConfig field won't allow saving of config

### ISSUE THREAD

**Issue by adavies25** [urbanairship/ua-unity-plugin#90]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Urban Airship dependencies are you using?
UA Plugin 6.0.1 

### What are the versions of any relevant development tools you are using?
Unity 2019.1.6f1

# Report

### What unexpected behavior are you seeing?
Error when saving config. Cannot deserialize type 'UrbanAirship.Editor.UAConfig' because it contains property 'GCMSenderId' which has no public setter.

### What is the expected behavior?
For the config to save.

### What are the steps to reproduce the unexpected behavior?
Open Window -> Urban Airship -> Settings. Type in your config and hit save.

### Do you have logging for the issue?
No

**Comment by rlepinski** [comment]
Interesting. Is this a project that you updated the plugin in?

**Comment by rlepinski** [comment]
Looks like we fixed this but the fix is not released yet. The sender ID is now optional since we normally pull it from the google-services.json file now. You can fix this in your project by deleting the GCMSenderId line from `ProjectSettings/UrbanAirship.xml`

**Comment by adavies25** [comment]
Thanks.
