### ISSUE TITLE
Gradle build fails when it can't find style/MessageCenter

### ISSUE THREAD

**Issue by adavies25** [urbanairship/ua-unity-plugin#91]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Urban Airship dependencies are you using?
UA Plugin 6.0.1

### What are the versions of any relevant development tools you are using?
Unity 2019.1.6f1

# Report

### What unexpected behavior are you seeing?
Building to Android fails in gradle processReleaseResources task:
  error: resource style/MessageCenter (aka com.adavies.shits:style/MessageCenter) not found.

### What is the expected behavior?
For the build not to fail.

### What are the steps to reproduce the unexpected behavior?
Install the plugin and build to an android phone

### Do you have logging for the issue?
FAILURE: Build failed with an exception.
Execution failed for task ':processReleaseResources'.
  error: resource style/MessageCenter (aka com.adavies.shits:style/MessageCenter) not found.

**Comment by rlepinski** [comment]
Could you provide details on your environment please? Is this an upgrade from an older plugin?

**Comment by rlepinski** [comment]
Assuming you are coming from an older version of the plugin, what is most likely happening is an old plugin file did not get cleaned up in the migration. Could you list any `urbanairship` folders or resources you see in the `Plugins/Android/` folder ?

**Comment by adavies25** [comment]
> Could you provide details on your environment please? Is this an upgrade from an older plugin?

No this is from a clean project in Unity 2019.1.6f1. I just imported the urban airship 6.0.1 unity package.
If I don't do anything I get missing style MessageCenter and if I do PlayServices Resolver -> Android -> Resolve it succeeds but when I build it's missing AirshipReceiver.

Here is my Plugins/Android folder:
    Directory: D:\UnityTestProjects\TestAirship\Assets\Plugins\Android


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/13/2019  12:02 PM                urbanairship-resources
-a----        6/13/2019  12:11 PM          22979 cardview-v7-26.0.2.aar
-a----        6/13/2019  12:11 PM            623 cardview-v7-26.0.2.aar.meta
-a----        6/13/2019  12:11 PM         417180 play-services-base-11.4.0.aar
-a----        6/13/2019  12:11 PM            623 play-services-base-11.4.0.aar.meta
-a----        6/13/2019  12:11 PM         388036 play-services-basement-11.4.0.aar
-a----        6/13/2019  12:11 PM            623 play-services-basement-11.4.0.aar.meta
-a----        6/13/2019  12:11 PM          81099 play-services-gcm-11.4.0.aar
-a----        6/13/2019  12:11 PM            623 play-services-gcm-11.4.0.aar.meta
-a----        6/13/2019  12:11 PM          16205 play-services-iid-11.4.0.aar
-a----        6/13/2019  12:11 PM            623 play-services-iid-11.4.0.aar.meta
-a----        6/13/2019  12:11 PM          29620 play-services-tasks-11.4.0.aar
-a----        6/13/2019  12:11 PM            623 play-services-tasks-11.4.0.aar.meta
-a----        6/13/2019  12:11 PM          24712 support-annotations-26.0.2.jar
-a----        6/13/2019  12:11 PM            623 support-annotations-26.0.2.jar.meta
-a----        6/13/2019  12:11 PM         635722 support-compat-26.0.2.aar
-a----        6/13/2019  12:11 PM            623 support-compat-26.0.2.aar.meta
-a----        6/13/2019  12:11 PM         232915 support-core-ui-26.0.2.aar
-a----        6/13/2019  12:11 PM            623 support-core-ui-26.0.2.aar.meta
-a----        6/13/2019  12:11 PM          87090 support-core-utils-26.0.2.aar
-a----        6/13/2019  12:11 PM            623 support-core-utils-26.0.2.aar.meta
-a----        6/13/2019  12:11 PM         163959 support-fragment-26.0.2.aar
-a----        6/13/2019  12:11 PM            623 support-fragment-26.0.2.aar.meta
-a----        6/13/2019  12:11 PM         311896 support-media-compat-26.0.2.aar
-a----        6/13/2019  12:11 PM            623 support-media-compat-26.0.2.aar.meta
-a----        6/13/2019  12:11 PM           3086 support-v4-26.0.2.aar
-a----        6/13/2019  12:11 PM            623 support-v4-26.0.2.aar.meta
-a----        6/13/2019  12:11 PM          17248 unity-plugin-4.4.0.aar
-a----        6/13/2019  12:11 PM            623 unity-plugin-4.4.0.aar.meta
-a----        3/13/2018   7:44 PM            429 urbanairship-resources.meta
-a----        6/13/2019  12:11 PM         915081 urbanairship-sdk-8.9.4.aar
-a----        6/13/2019  12:11 PM            623 urbanairship-sdk-8.9.4.aar.meta


    Directory: D:\UnityTestProjects\TestAirship\Assets\Plugins\Android\urbanairship-resources


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/13/2019  12:02 PM                res
-a----        3/13/2018   7:44 PM            298 AndroidManifest.xml
-a----        3/13/2018   7:44 PM            178 AndroidManifest.xml.meta
-a----        3/13/2018   7:44 PM             38 project.properties
-a----        3/13/2018   7:44 PM            175 project.properties.meta
-a----        6/13/2019  12:02 PM            172 res.meta


    Directory: D:\UnityTestProjects\TestAirship\Assets\Plugins\Android\urbanairship-resources\res


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/13/2019  12:02 PM                xml
-a----        6/13/2019  12:02 PM            172 xml.meta


    Directory: D:\UnityTestProjects\TestAirship\Assets\Plugins\Android\urbanairship-resources\res\xml


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/13/2019   1:35 PM            371 airship_config.xml
-a----        6/13/2019  12:02 PM            155 airship_config.xml.meta

**Comment by adavies25** [comment]
I'm also using the sdk, ndk and gradle provided with Unity and no custom gradle template.

**Comment by rlepinski** [comment]
@adavies25 It looks like you pulled in the 4.4.0 version of the plugin and not 6.0.1. Please redownload the latest plugin and try that.

**Comment by adavies25** [comment]
I apologize. I was trying to make things work by rolling back versions. This time I created a new clean project and just imported in the UA 6.0.1 plugin and still get style/MessageCenter gradle error when building. If I do Assets->Play Services Resolver->Android Resolver->Resolve, the resolve succeeds but I get a different error: 
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.
D8: Program type already present: com.urbanairship.unityplugin.CustomMessageCenterActivity

I'm building for ARM7 and ARM64 using IL2CPP.

Thank you for your help and also the quick responses.

Here is my clean project Plugins/Android listing:
PS D:\UnityTestProjects\TestAirshipAgain\Assets\Plugins\Android> Get-ChildItem -Recurse


    Directory: D:\UnityTestProjects\TestAirshipAgain\Assets\Plugins\Android


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/14/2019  10:24 AM                urbanairship-resources
-a----        6/14/2019  10:42 AM          11567 android.arch.core.common-1.1.1.jar
-a----        6/14/2019  10:42 AM            623 android.arch.core.common-1.1.1.jar.meta
-a----        6/14/2019  10:42 AM           5124 android.arch.core.runtime-1.1.1.aar
-a----        6/14/2019  10:42 AM            623 android.arch.core.runtime-1.1.1.aar.meta
-a----        6/14/2019  10:42 AM          20618 android.arch.lifecycle.common-1.1.1.jar
-a----        6/14/2019  10:42 AM            623 android.arch.lifecycle.common-1.1.1.jar.meta
-a----        6/14/2019  10:42 AM          10073 android.arch.lifecycle.livedata-1.1.1.aar
-a----        6/14/2019  10:42 AM            623 android.arch.lifecycle.livedata-1.1.1.aar.meta
-a----        6/14/2019  10:42 AM           9142 android.arch.lifecycle.livedata-core-1.1.1.aar
-a----        6/14/2019  10:42 AM            623 android.arch.lifecycle.livedata-core-1.1.1.aar.meta
-a----        6/14/2019  10:42 AM           9635 android.arch.lifecycle.runtime-1.1.1.aar
-a----        6/14/2019  10:42 AM            623 android.arch.lifecycle.runtime-1.1.1.aar.meta
-a----        6/14/2019  10:42 AM           7217 android.arch.lifecycle.viewmodel-1.1.1.aar
-a----        6/14/2019  10:42 AM            623 android.arch.lifecycle.viewmodel-1.1.1.aar.meta
-a----        6/14/2019  10:42 AM           7915 com.android.support.asynclayoutinflater-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.asynclayoutinflater-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          42329 com.android.support.collections-28.0.0.jar
-a----        6/14/2019  10:42 AM            623 com.android.support.collections-28.0.0.jar.meta
-a----        6/14/2019  10:42 AM          44453 com.android.support.coordinatorlayout-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.coordinatorlayout-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          10686 com.android.support.cursoradapter-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.cursoradapter-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          33513 com.android.support.customview-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.customview-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          11266 com.android.support.documentfile-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.documentfile-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          32585 com.android.support.drawerlayout-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.drawerlayout-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM           7761 com.android.support.interpolator-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.interpolator-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          33702 com.android.support.loader-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.loader-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM           6905 com.android.support.localbroadcastmanager-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.localbroadcastmanager-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          16016 com.android.support.print-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.print-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          23673 com.android.support.slidingpanelayout-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.slidingpanelayout-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          27865 com.android.support.support-annotations-28.0.0.jar
-a----        6/14/2019  10:42 AM            623 com.android.support.support-annotations-28.0.0.jar.meta
-a----        6/14/2019  10:42 AM         619633 com.android.support.support-compat-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.support-compat-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          11398 com.android.support.support-core-ui-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.support-core-ui-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM           4190 com.android.support.support-core-utils-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.support-core-utils-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM         157597 com.android.support.support-fragment-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.support-fragment-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM         337831 com.android.support.support-media-compat-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.support-media-compat-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM           2951 com.android.support.support-v4-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.support-v4-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          33133 com.android.support.swiperefreshlayout-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.swiperefreshlayout-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          26936 com.android.support.versionedparcelable-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.versionedparcelable-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM          53814 com.android.support.viewpager-28.0.0.aar
-a----        6/14/2019  10:42 AM            623 com.android.support.viewpager-28.0.0.aar.meta
-a----        6/14/2019  10:42 AM         389850 com.google.android.gms.play-services-base-16.0.1.aar
-a----        6/14/2019  10:42 AM            623 com.google.android.gms.play-services-base-16.0.1.aar.meta
-a----        6/14/2019  10:42 AM         197649 com.google.android.gms.play-services-basement-16.0.1.aar
-a----        6/14/2019  10:42 AM            623 com.google.android.gms.play-services-basement-16.0.1.aar.meta
-a----        6/14/2019  10:42 AM          16069 com.google.android.gms.play-services-stats-16.0.1.aar
-a----        6/14/2019  10:42 AM            623 com.google.android.gms.play-services-stats-16.0.1.aar.meta
-a----        6/14/2019  10:42 AM          27267 com.google.android.gms.play-services-tasks-16.0.1.aar
-a----        6/14/2019  10:42 AM            623 com.google.android.gms.play-services-tasks-16.0.1.aar.meta
-a----        6/14/2019  10:42 AM          49793 com.google.firebase.firebase-common-16.0.3.aar
-a----        6/14/2019  10:43 AM            623 com.google.firebase.firebase-common-16.0.3.aar.meta
-a----        6/14/2019  10:42 AM          63498 com.google.firebase.firebase-iid-17.0.4.aar
-a----        6/14/2019  10:42 AM            623 com.google.firebase.firebase-iid-17.0.4.aar.meta
-a----        6/14/2019  10:42 AM           6656 com.google.firebase.firebase-iid-interop-16.0.1.aar
-a----        6/14/2019  10:42 AM            623 com.google.firebase.firebase-iid-interop-16.0.1.aar.meta
-a----        6/14/2019  10:42 AM           7993 com.google.firebase.firebase-measurement-connector-17.0.1.aar
-a----        6/14/2019  10:42 AM            623 com.google.firebase.firebase-measurement-connector-17.0.1.aar.meta
-a----        6/14/2019  10:42 AM          59645 com.google.firebase.firebase-messaging-17.3.4.aar
-a----        6/14/2019  10:42 AM            623 com.google.firebase.firebase-messaging-17.3.4.aar.meta
-a----        6/14/2019  10:43 AM          17656 com.urbanairship.android.unity-plugin-6.0.1.aar
-a----        6/14/2019  10:43 AM            623 com.urbanairship.android.unity-plugin-6.0.1.aar.meta
-a----        6/14/2019  10:43 AM        1286427 com.urbanairship.android.urbanairship-core-9.7.1.aar
-a----        6/14/2019  10:43 AM            623 com.urbanairship.android.urbanairship-core-9.7.1.aar.meta
-a----        6/14/2019  10:42 AM          11694 com.urbanairship.android.urbanairship-fcm-9.7.1.aar
-a----        6/14/2019  10:42 AM            623 com.urbanairship.android.urbanairship-fcm-9.7.1.aar.meta
-a----        3/14/2019   9:23 PM            549 urbanairship-resources.meta


    Directory: D:\UnityTestProjects\TestAirshipAgain\Assets\Plugins\Android\urbanairship-resources


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/14/2019  10:24 AM                res
-a----        3/14/2019   9:23 PM            298 AndroidManifest.xml
-a----        3/14/2019   9:23 PM            155 AndroidManifest.xml.meta
-a----        3/14/2019   9:23 PM             38 project.properties
-a----        3/14/2019   9:23 PM            155 project.properties.meta
-a----        6/14/2019  10:24 AM            172 res.meta


    Directory: D:\UnityTestProjects\TestAirshipAgain\Assets\Plugins\Android\urbanairship-resources\res


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/14/2019  10:25 AM                values
d-----        6/14/2019  10:24 AM                xml
-a----        6/14/2019  10:24 AM            172 values.meta
-a----        6/14/2019  10:24 AM            172 xml.meta


    Directory: D:\UnityTestProjects\TestAirshipAgain\Assets\Plugins\Android\urbanairship-resources\res\values


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/14/2019  10:43 AM            957 values.xml
-a----        6/14/2019  10:25 AM            155 values.xml.meta


    Directory: D:\UnityTestProjects\TestAirshipAgain\Assets\Plugins\Android\urbanairship-resources\res\xml


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/14/2019  10:43 AM            317 airship_config.xml
-a----        6/14/2019  10:24 AM            155 airship_config.xml.meta

**Comment by rlepinski** [comment]
Not sure why it would fail. I am downloading the newest version of unity to see whats going on.

I am pretty sure the issue is with an old version of the Play Services Resolver. While my machine is updating, any chance you can try https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.117.0.unitypackage and force resolve again?

**Comment by rlepinski** [comment]
I was able to get it to build after having the same issues.

GCMSenderId issue:
Assets -> Urban Airship -> Editor -> UAConfig:
Make the GCMSenderId property have a public setter

`com.urbanairship.unityplugin.CustomMessageCenterActivity` issue:

For whatever reason the Android AAR is being included twice. Navigate to
Assets -> Urban Airship -> m2repository -> com -> urbanairship -> android -> unity plugin -> 6.0.1

Make sure every file is not included in any platform
<img width="397" alt="Screen Shot 2019-06-14 at 5 54 46 PM" src="https://user-images.githubusercontent.com/3967591/59521854-8c03a600-8ecd-11e9-8ae9-5633cf2bbca5.png">

Ill see if I can address this in the next week or so.

**Comment by adavies25** [comment]
That works! Thank you so much for this workaround and the quick responses. We are submitting our app on Monday. Always crunched for time at the last minute..always. Much appreciated.
