### ISSUE TITLE
Unable to merge android manifests

### ISSUE THREAD

**Issue by shushka5762** [urbanairship/ua-unity-plugin#95]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

{
  "dependencies": {}
}
### What are the versions of any relevant development tools you are using?

Running in Windows 10 inside Parallels on an Apple iMac.
Unity 2018.1.9f2 (64bit).
Build Android SDK Minimum API Level: Android 5.1 'Lollipop' (API Level 22).
Build Android SDK Target API Level: Automatic (highest installed) ==> API Level 29 Revision 3.
# Report
Other than the latest UrbanAirship no other packages are installed.
One small Java plugin is installed that simply calls a couple Java WiFi status reporting and changing functions, which are called using the standard Unity Java functions calling convention.
Code builds without the UrbanAirship plugin but fails to build with it.
An example UrbanAirship app that you provide builds and runs OK.
### What unexpected behavior are you seeing?

Error message during build: Unable to merge android manifests.
### What is the expected behavior?

No error.
### What are the steps to reproduce the unexpected behavior?

Build.
### Do you have logging for the issue?

Unity Editor Error Message:
AndroidSDKToolsException: Unable to merge android manifests. 
UnityEditor.Android.AndroidSDKTools.DetectErrorsAndWarnings (System.String logMessages, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommand (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommand (System.String[] sdkToolCommand, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.MergeManifests (System.String target, System.String mainManifest, System.String[] libraryManifests, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit)
UnityEditor.Android.PostProcessor.Tasks.GenerateManifest.MergeManifests (UnityEditor.Android.PostProcessor.PostProcessorContext context, System.String mainManifest, System.String targetManifest)
UnityEditor.Android.PostProcessor.Tasks.GenerateManifest.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by shushka5762** [comment]
Additional critical information:

There is an AndroidManifest.xml file in the Plugins folder that my Java plugins require. If this file is removed, the apk is build with no errors. If I put it back into the Plugins folder or into the Android subfolder of the Plugins folder the build fails due to the Unable to merge android manifests error. I do need this AndroidManifest.xml or its equivalent for my apk to function. The  AndroidManifest.xml file is attached as an AndroidManifest.txt file.
[AndroidManifest.txt](https://github.com/urbanairship/ua-unity-plugin/files/3666657/AndroidManifest.txt)

**Comment by BrianBatchelder** [comment]
Unity generates an error during the manifest merge process if there is something that conflicts between the manifests. An example of this would be `Main manifest has <uses-sdk android:targetSdkVersion='23'> but library uses targetSdkVersion='24'`. I do not see an error like this in the log you posted above. 
Can you please take another look at the failure and see if there is any more information above or below the logging you posted? It might even be logged somewhere else like stderr, while the stack trace is logged to stdout.

**Comment by shushka5762** [comment]
Dear Brian,

I do not see any additional error logs. I, however, have a “solution” although it is not completely satisfactory. I had replaced the automatically generated AndroidManifest.xml in the "urbanairship-resources" directory with the following one:

<?xml version="1.0" encoding="utf-8"?>

<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.unity3d.player"
	android:installLocation="preferExternal"
	android:theme="@android:style/Theme.NoTitleBar"
    android:versionCode="1"
    android:versionName="1.0">
    <supports-screens
        android:smallScreens="true"
        android:normalScreens="true"
        android:largeScreens="true"
        android:xlargeScreens="true"
        android:anyDensity="true"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"></uses-permission>
  <uses-permission android:name="android.permission.REBOOT"></uses-permission>
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"></uses-permission>
  <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"></uses-permission>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"></uses-permission>

  <application
		android:icon="@drawable/app_icon"
        android:label="@string/app_name"
        android:debuggable="true">
        <activity android:name="com.unity3d.player.UnityPlayerNativeActivity"
                  android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
            </intent-filter>
            <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
            <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
        </activity>
    </application>
</manifest>

Where the commented out portion at the beginning is the original AndroidManifest.xml and the new part below is the AndroidManifest.xml that my java code required. This builds without any errors. I hope this will help you in your investigation.

Dmitry Volovik

**Comment by BrianBatchelder** [comment]
I have been unable to reproduce your issue. Unity was able to merge your sample manifest without issue. I am using Unity version 2019.2.7f2.

My build produced a report, `Temp/gradleOut/build/outputs/logs/manifest-merger-debug-report.txt`. Could you take a look for that file and post it here? It might give us further clues.

**Comment by BrianBatchelder** [comment]
Please let us know if you have further issues.
