### ISSUE TITLE
Unity Firebase Analytics conflict with Urban Airship dependencies

### ISSUE THREAD

**Issue by adavies25** [urbanairship/ua-unity-plugin#99]
# Preliminary Info

### What Airship dependencies are you using?

urbanairship-6.2.0.unitypackage

### What are the versions of any relevant development tools you are using?

# Report
Unity 2019.3.0f6
urbanairship-6.2.0.unitypackage
firebase_unity_sdk_6.10.0/dotnet4/FirebaseAnalytics.unitypackage

### What unexpected behavior are you seeing?

Android Playservices resolver finds conflicts between the two packages and tries to download newer package versions. This succeeds in resolution. However when the app runs, the UnityAndroid class is constructed through JNI and fails because it's missing classes because of the newer resolved AARs. The backend airship process runs, but the C# side is stuck and push notifications can't be enabled.

### What is the expected behavior?

Playservices resolver to not find conflicts between Airship and Firebase Analytics and leave urban airship files alone.

### What are the steps to reproduce the unexpected behavior?

1. Create a new Project in Unity 2019.3.0f6.
2. Import custom package urbanairship-6.2.0.unitypackage
3. Import custom package firebase_unity_sdk_6.10.0/dotnet4/FirebaseAnalytics.unitypackage
4. Deleted the obsolete files is suggests to delete.
5. Restart Unity because it can't resolve if you don't.
6. Assets -> Play Services Resolver -> Android Resolver -> Resolve
7. Notice the conflict warning log message in the console
8. Create an empty scene with a camera and put the UA example script on the camera.
9. Build to Android phone
10. Notice in the logcat logs "UAirship plugin not found"

### Do you have logging for the issue?

Yes see below.

Here is an image of the library conflict:
![conflicted](https://user-images.githubusercontent.com/14877009/75299798-0548ec00-5804-11ea-8e59-72bf6db68758.PNG)
After the resolve succeeds I now have com.urbanairship.android.urbanairship-fcm-12.2.0.aar instead of ..fcm-10.1.3.aar
![libraries](https://user-images.githubusercontent.com/14877009/75299935-607ade80-5804-11ea-9633-dd9ea8bd2c60.PNG)
In order to get more verbose logs of the problem I changed this piece of code:
![untouched code](https://user-images.githubusercontent.com/14877009/75299962-7f797080-5804-11ea-86a7-da110b106e52.PNG)
Into this piece of code:
![code changed](https://user-images.githubusercontent.com/14877009/75299977-8acc9c00-5804-11ea-90f0-de02de5f125c.PNG)
Finally here is the logcat logs of the error missing the class:
01/01 00:00:00.000 -1 -1 Info : 02-25 19:00:12.202  9024  9054 I TestAirship - UALib: Airship taking off!
01/01 00:00:00.000 -1 -1 Info : 02-25 19:00:12.202  9024  9054 I TestAirship - UALib: Airship log level: 3
01/01 00:00:00.000 -1 -1 Info : 02-25 19:00:12.202  9024  9054 I TestAirship - UALib: UA Version: 12.2.0 / App key = VT8fsEd0Q2KZBrEF1W-reQ Production = false
01/01 00:00:00.000 -1 -1 Info : 02-25 19:00:12.260  9024  9054 I TestAirship - UALib: Using push provider: FCM Push Provider

......snipped.......

02/25 19:00:14.836 9024 9056 Error Unity: UAirship plugin not found. Reason: UnityEngine.AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/urbanairship/push/TagGroupsEditor;
02/25 19:00:14.836 9024 9056 Error Unity:   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
02/25 19:00:14.836 9024 9056 Error Unity:   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0 
02/25 19:00:14.836 9024 9056 Error Unity:   at UnityEngine.AndroidReflection.GetMethodMember (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
02/25 19:00:14.836 9024 9056 Error Unity:   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
02/25 19:00:14.836 9024 9056 Error Unity:   at UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
02/25 19:00:14.836 9024 9056 Error Unity:   at UrbanAirship.UAirs
01/01 00:00:00.000 -1 -1 Info : 02-25 19:00:22.540  9024  9058 D TestAirship - UALib: EventApiClient - Sending analytics events. Request: com.urbanairship.http.Request@2ddd728 Events: [{"event_id":"4e1f9d37-1fd2-4043-9bf4-4e273f7d6e83","time":"1582675212.286","data":{"daylight_savings":false,"carrier":"","package_version":"0.1","connection_type":"wifi","connection_subtype":"","os_version":"10","session_id":"ba222c28-27d3-497d-9f0c-f4a51fd51009","time_zone":-18000,"lib_version":"12.2.0"},"type":"app_foreground"}]
01/01 00:00:00.000 -1 -1 Info : 02-25 19:00:22.698  9024  9058 D TestAirship - UALib: EventApiClient - Analytics event response: Response{responseBody='', responseHeaders={null=[HTTP/1.1 200 OK], Alt-Svc=[clear], Content-Type=[application/json], Date=[Wed, 26 Feb 2020 00:00:22 GMT], Transfer-Encoding=[chunked], Via=[1.1 google], X-Android-Received-Millis=[1582675222695], X-Android-Response-Source=[NETWORK 200], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1582675222667], X-UA-Max-Batch=[500], X-UA-Max-Total=[5120], X-UA-Max-Wait=[604800000], X-UA-Min-Batch-Interval=[60000]}, status=200, responseMessage='OK', lastModified=0}
01/01 00:00:00.000 -1 -1 Info : 02-25 19:00:22.700  9024  9058 D TestAirship - UALib: EventManager - Analytic events uploaded.

**Comment by crow** [comment]
@adavies25 Looking into it, thanks for reporting

**Comment by rlepinski** [comment]
Should be resolved in our upcoming release. Its an issue with androidx migration which the current plugin is not built for, so it updates to our plugin that is androidx compatible but that version is incompatible. If you can force version 11.+ instead of `+` it might work, or you need to wait for the new release.

**Comment by rlepinski** [comment]
Fixed in 7.0.0

**Comment by adavies25** [comment]
Thank you!
